[package]

name = "sniff-me"
version = "0.0.1"
authors = [ "Warsame Bashir <warsame.bashir@bixinsoftware.com>", "Franco Ross <franco.ross@ymail.com>" , "Charles Uchidiuno <charlesu@gmail.com>" ]

[[bin]]

name = "main"
